# Generated by Django 6.0.2 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
