# Generated by Django 6.0.2 on 2026-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0003_patientrecord_email_patientrecord_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='expiration_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
