# Generated by Django 6.0.2 on 2026-03-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0004_balance_active_balance_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], default='credit', max_length=10),
        ),
    ]
