# Generated by Django 6.0.2 on 2026-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0005_alter_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.CharField(choices=[('consulta', 'Consulta'), ('plano_3', 'Plano 3'), ('plano_6', 'Plano 6')], default='consulta', max_length=10),
        ),
    ]
