# Generated by Django 6.0.3 on 2026-03-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0007_alter_balance_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expiration_days', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='aliada.balanceplan'),
        ),
    ]
