# Generated by Django 6.0.3 on 2026-03-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0008_balanceplan_alter_balance_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceplan',
            name='value',
        ),
        migrations.AddField(
            model_name='balanceplan',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
