# Generated by Django 6.0.2 on 2026-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0011_balanceplan_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='amount_medical',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='amount_nutrition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balance',
            name='nutrition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balanceplan',
            name='percentage_medical',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balanceplan',
            name='percentage_nutrition',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
