# Generated by Django 6.0.2 on 2026-03-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliada', '0012_balance_amount_medical_balance_amount_nutrition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='medical',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='balanceplan',
            name='medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='balanceplan',
            name='nutrition',
            field=models.BooleanField(default=False),
        ),
    ]
